Repository DeveloperAcademy-POSTECH/MC3-Team15-Wavegram, pull requests merged in 2022-08, with the labels that each got.

#87 [Design] MainView Font 적용
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/HomeViewController.swift
  Wavegram/Wavegram/Info.plist
  Wavegram/Wavegram/Resources/Font/RockSalt.ttf
  Wavegram/Wavegram/Views/HomeFeedCollectionViewCell.swift
Labels: chore

#86 [Feat] NewUploadViewController 익스텐션 일부 분리
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Extension/NewUploadViewExtension.swift
Labels: feat

#90 [Feat] HomeViewController Feats
  Wavegram/Wavegram/Controllers/HomeViewController.swift
  Wavegram/Wavegram/Views/HomeFeedCollectionViewCell.swift
Labels: feat

#91 [Feat] Segment 선택시 Feeds 변화
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/UserViewController.swift
  Wavegram/Wavegram/Managers/DataManager.swift
  Wavegram/Wavegram/Resources/Jsons/UserContributedFeeds.json
  Wavegram/Wavegram/Resources/Jsons/UserOwnedFeeds.json
  Wavegram/Wavegram/Views/UserFeedCollectionReusableView.swift
Labels: bugfix, feat

#92 Data연결 upload관련vc들
  Wavegram/Wavegram/Controllers/ContributionUploadViewController.swift
  Wavegram/Wavegram/Controllers/HomeViewController.swift
  Wavegram/Wavegram/Controllers/ModifyPostViewController.swift
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/bulgogi.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/bulgogi.imageset/bulgogi.jpeg
  Wavegram/Wavegram/Views/HomeFeedCollectionViewCell.swift
Labels: feat
