Repository DeveloperAcademy-POSTECH/MC3-Team15-Wavegram, pull requests merged in 2022-07, with the labels that each got.

#2 [Feat] JsonManager
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Base.lproj/LaunchScreen.storyboard
  Wavegram/Wavegram/Extension/Extensions.swift
  Wavegram/Wavegram/Managers/JsonManager.swift
  Wavegram/Wavegram/Models/FeedModel.swift
  Wavegram/Wavegram/Models/UserModel.swift
  Wavegram/Wavegram/Models/WavegramModel.xcdatamodeld/WavegramModel.xcdatamodel/contents
  Wavegram/Wavegram/Resources/AppDelegate.swift
  Wavegram/Wavegram/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/Contents.json
  Wavegram/Wavegram/Resources/Feed.json
  Wavegram/Wavegram/Resources/SceneDelegate.swift
Labels: enhancement

#8 [Refactor] tabBarItem naming
  Wavegram/Wavegram/Controllers/MainTabBarViewController.swift
Labels: documentation

#7 [Feat] Modify post 작업
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/ModifyPostViewController.swift
  Wavegram/Wavegram/Extension/LayerExtension.swift
  Wavegram/Wavegram/Extension/TextFieldExtension.swift
  Wavegram/Wavegram/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ModifyPost/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ModifyPost/testImage1.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ModifyPost/testImage1.imageset/KakaoTalk_Photo_2022-07-06-15-56-2.jpeg
Labels: feat

#12 스펙트로그램 코드 업데이트
  Wavegram/Wavegram/Spectrogram/SpecgtrogramAVCaptureAudioDataOutputSampleBufferDelegate.swift
  Wavegram/Wavegram/Spectrogram/Spectrogram.swift
Labels: feat

#13 [Feat] [Add] UserViewController
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/UserViewController.swift
  Wavegram/Wavegram/Resources/Assets.xcassets/someImage.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/someImage.imageset/someImage.jpg
  Wavegram/Wavegram/Resources/Assets.xcassets/woodyProfileImage.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/woodyProfileImage.imageset/woodyProfileImage.jpg
  Wavegram/Wavegram/Resources/SingleFeedViewController.swift
  Wavegram/Wavegram/Resources/UserViewFeedCollectionViewCell.swift
Labels: refactor

#14 [Refactor] Test Files Deletion
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/WavegramTests/WavegramTests.swift
  Wavegram/WavegramUITests/WavegramUITests.swift
  Wavegram/WavegramUITests/WavegramUITestsLaunchTests.swift
Labels: wontfix

#15 디렉토리 패스 수정
  Wavegram/Wavegram/Views/SingleFeedViewController.swift
  Wavegram/Wavegram/Views/Spectrogram.swift
  Wavegram/Wavegram/Views/UserViewFeedCollectionViewCell.swift
Labels: bug, refactor

#24 [Refactor] UserViewController, SearchViewController
  Wavegram/Wavegram/Controllers/SearchViewController.swift
  Wavegram/Wavegram/Controllers/UserViewController.swift
Labels: refactor

#26 [Feat] DARK MODE 추가
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Info.plist
  Wavegram/Wavegram/Models/UserModel.swift
Labels: feat

#23 Set dark mode as default
  Wavegram/.DS_Store
  Wavegram/.idea/.gitignore
  Wavegram/.idea/Wavegram.iml
  Wavegram/.idea/modules.xml
  Wavegram/.idea/shelf/Uncommitted_changes_before_Checkout_at_7_22_22,_3_33_PM_[Changes]/UserInterfaceState.xcuserstate
  Wavegram/.idea/shelf/Uncommitted_changes_before_Checkout_at_7_22_22,_3_33_PM_[Changes]/shelved.patch
  Wavegram/.idea/shelf/Uncommitted_changes_before_Checkout_at_7_22_22__3_33_PM__Changes_.xml
  Wavegram/.idea/vcs.xml
  Wavegram/.idea/workspace.xml
  Wavegram/.idea/xcode.xml
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram.xcodeproj/project.xcworkspace/xcuserdata/raymondkim.xcuserdatad/UserInterfaceState.xcuserstate
  Wavegram/Wavegram.xcodeproj/project.xcworkspace/xcuserdata/raymondkim.xcuserdatad/xcschemes/xcschememanagement.plist
  Wavegram/Wavegram.xcodeproj/xcuserdata/raymondkim.xcuserdatad/xcschemes/Wavegram.xcscheme
  Wavegram/Wavegram.xcodeproj/xcuserdata/raymondkim.xcuserdatad/xcschemes/xcschememanagement.plist
  Wavegram/Wavegram/.DS_Store
  Wavegram/Wavegram/Controllers/HomeViewController.swift
  Wavegram/Wavegram/Controllers/MainTabBarViewController.swift
  Wavegram/Wavegram/Controllers/ModifyPostViewController.swift
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Controllers/RecordButton.swift
  Wavegram/Wavegram/Controllers/RecordButtonController.swift
  Wavegram/Wavegram/Controllers/RecordButtonKit.swift
  Wavegram/Wavegram/Controllers/UserViewController.swift
  Wavegram/Wavegram/Extension/SpectrogramExtension.swift
  Wavegram/Wavegram/Info.plist
  Wavegram/Wavegram/Resources/.DS_Store
  Wavegram/Wavegram/Resources/AppDelegate.swift
  Wavegram/Wavegram/Resources/SingleFeedViewController.swift
  Wavegram/Wavegram/Resources/UserViewFeedCollectionViewCell.swift
  Wavegram/Wavegram/Spectrogram/Spectrogram.swift
  Wavegram/Wavegram/Views/SingleFeedViewController.swift
  Wavegram/Wavegram/Views/Spectrogram.swift
Labels: chore

#17 Capture session configuration
  .idea/.gitignore
  .idea/challenge_3.iml
  .idea/modules.xml
  .idea/vcs.xml
  Wavegram/Wavegram/.DS_Store
Labels: feat

#22 Adding previews to view controllers
  Wavegram/.DS_Store
  Wavegram/Wavegram/Extension/SpectrogramExtension.swift
Labels: chore

#35 [Add] Create home view
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/HomeViewController.swift
  Wavegram/Wavegram/Views/FeedCollectionViewCell.swift
Labels: feat

#37 [Feat] #1 폰트 익스텐션 등록
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Extension/Font.swift
  Wavegram/Wavegram/Info.plist
  Wavegram/Wavegram/Resources/Font/SFCompact.ttf
Labels: feat

#38 Single feed header UI
  Wavegram/Wavegram/Controllers/HomeViewController.swift
  Wavegram/Wavegram/Models/FeedModel.swift
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/woddyFeed.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/woddyFeed.imageset/스크린샷 2022-07-13 오후 3.44.36.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/aliceProfile.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/aliceProfile.imageset/스크린샷 2022-07-13 오후 5.38.33.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/milkyProfile.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/milkyProfile.imageset/스크린샷 2022-07-13 오후 8.16.00.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/woodyProfile.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/woodyProfile.imageset/woodyProfile.png
  Wavegram/Wavegram/Views/FeedCollectionViewCell.swift
Labels: feat

#41 [Fix] Spectrogram 에러 픽스
  Wavegram/Wavegram/Extension/SpectrogramExtension.swift
  Wavegram/Wavegram/Views/Spectrogram.swift
Labels: bugfix, refactor

#43 [Fix] 폰트 및 폰트 익스텐션, Extensions.swift 파일 참조 오류 해결
  Wavegram/Wavegram/Extension/Extensions.swift
  Wavegram/Wavegram/Extension/FontExtension.swift
Labels: bugfix

#45 [Fix] 빌드 또(...) 오류로 리버트 후 푸시
  Wavegram/Wavegram/Extension/FontExtension.swift
Labels: bugfix

#46 [Chore] 앱 구동화면 원복 및 프리뷰 코드 주석처리
  Wavegram/.idea/workspace.xml
  Wavegram/Wavegram.xcodeproj/project.xcworkspace/xcuserdata/raymondkim.xcuserdatad/UserInterfaceState.xcuserstate
  Wavegram/Wavegram/Controllers/MainTabBarViewController.swift
  Wavegram/Wavegram/Controllers/ModifyPostViewController.swift
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Controllers/UserViewController.swift
  Wavegram/Wavegram/Resources/SceneDelegate.swift
Labels: chore

#50 [Fix] 드디어 해결했습니다
  Wavegram/Wavegram/Controllers/MainTabBarViewController.swift
  Wavegram/Wavegram/Controllers/ModifyPostViewController.swift
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Controllers/UserViewController.swift
  Wavegram/Wavegram/Resources/SceneDelegate.swift
Labels: bugfix

#54 [Chore] 폰트 익스텐션 추가 및 빈 서브모듈 삭제
  Wavegram/Wavegram.xcodeproj/project.xcworkspace/xcuserdata/raymondkim.xcuserdatad/UserInterfaceState.xcuserstate
Labels: feat, chore

#63 New Upload VC 작업
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/pauseButton.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/pauseButton.imageset/pauseButton.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/pauseButton.imageset/pauseButton2.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/playButton.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/playButton.imageset/playButton.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/playButton.imageset/playButton2.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/recordButton.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/recordButton.imageset/recordButton.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/recordButton.imageset/recordButton2.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/stopButton.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/stopButton.imageset/stopButton.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/stopButton.imageset/stopButton2.png
Labels: feat, refactor

#66 [Feat] 스펙트로그램 중지 함수 작성
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram.xcodeproj/project.xcworkspace/xcuserdata/raymondkim.xcuserdatad/UserInterfaceState.xcuserstate
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Extension/SpectrogramExtension.swift
Labels: feat

#67 New uploadVC 테스트 음원 재생 작업
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/NewUploadViewController.swift
  Wavegram/Wavegram/Resources/Audio/GuitarAndVocal.mp3
  Wavegram/Wavegram/Resources/Audio/GuitarOnly.mp3
  Wavegram/Wavegram/Resources/Audio/VocalOnly.mp3
Labels: feat

#72 [Feat] UserSingleFeedView NavigationBar 관련 작업
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/UserSingleFeedViewController.swift
  Wavegram/Wavegram/Controllers/UserViewController.swift
Labels: feat

#74 [Feat] UserSingleFeedView Feed UI 작업
  Wavegram/Wavegram/Controllers/UserSingleFeedViewController.swift
  Wavegram/Wavegram/Views/HomeFeedCollectionViewCell.swift
Labels: feat

#77 [Chore] 스펙트로그램 뷰 컨트롤러 파일 삭제(주석처리)
  Wavegram/Wavegram/Controllers/SpectrogramViewController.swift
  Wavegram/Wavegram/Extension/SpectrogramExtension.swift
Labels: chore

#81 Contribution Upload VC 작업
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/ContributionUploadViewController.swift
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/mutedSpeaker.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/mutedSpeaker.imageset/speakerMuted.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/mutedSpeaker.imageset/speakerMuted2.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/speaker.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/speaker.imageset/speaker.png
  Wavegram/Wavegram/Resources/Assets.xcassets/ButtonImage/speaker.imageset/speaker2.png
Labels: feat

#82 [Design] NavBar Right Bar Button Item Size
  Wavegram/Wavegram/Controllers/UserViewController.swift
Labels: chore

#85 [Chore] Change HomeFeedCollectionViewCell Feats
  Wavegram/Wavegram.xcodeproj/project.pbxproj
  Wavegram/Wavegram/Controllers/HomeViewController.swift
  Wavegram/Wavegram/Resources/AllFeeds.swift
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/aliceFeed.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/aliceFeed.imageset/aliceFeed.png
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/drogbaFeed.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/FeedImage/drogbaFeed.imageset/drogbaFeed.jpeg
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/drogbaProfile.imageset/Contents.json
  Wavegram/Wavegram/Resources/Assets.xcassets/ProfileImage/drogbaProfile.imageset/KakaoTalk_Photo_2022-07-06-15-56-2.jpeg
  Wavegram/Wavegram/Views/HomeFeedCollectionViewCell.swift
Labels: chore
